server:
  # 端口号
  port: 8008
  context-path: /crm

spring:
  # 多环境
  profiles:
#    active: prod
    active: dev

  # 视图缓存
  thymeleaf:
    cache: false
  # 控制台多彩输出
  output:
    ansi:
      enabled: detect
  http:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 10Mb
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 50Mb
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

# 自定义属性
myProperties:
  # 1.bi
  yunzhijia:
    bi:
      # 云之家-兴齐眼药bi轻应用相关参数
      # 轻应用里配置的
      appId: 500040371
      # 轻应用里配置的
      appSecret: 123123
      utf8: UTF-8
      applicationJson: application/json
      applicationXWwwFormUrlEncoded: application/x-www-form-urlencoded
      timeoutMillis: 3000
      openApiHost: https://www.yunzhijia.com/openapi
      openAuth2Host: https://do.yunzhijia.com/openauth2
      # 获取access_token
      accessTokenUrl: ${myProperties.yunzhijia.bi.openAuth2Host}/api/appAuth2
      # 获取云之家APP当前登录用户上下文
      ticketToContextUrl: ${myProperties.yunzhijia.bi.openApiHost}/third/v1/ticket/public/tickettocontext
---
# 生产环境
spring:
  profiles: prod
  # crm 数据源
  datasource:
    master:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@172.16.119.56:1521:orcl
      username: crm
      password: crm

---
# 开发环境
spring:
  profiles: dev
  # crm 数据源
  datasource:
    master:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: crm
      password: crm

